/**
 * mcpDirectory.ts
 * ════════════════════════════════════════════════════════════════════════════════
 * Master Directory of 100 Remote HTTPS Model Context Protocol (MCP) Servers
 *
 * Categorized Directory of Remote Streamable HTTP / SSE Endpoints:
 *  1. Developer Docs, Code Repositories & Knowledge Engines (20)
 *  2. Web Search, Fetching & Public Crawlers (15)
 *  3. Database Connectors & Storage Engines (10)
 *  4. Social Media & Communication APIs (11)
 *  5. Cloud, Infrastructure, & DevOps Tools (10)
 *  6. OSINT, Cyber Security, & Data Validation (10)
 *  7. Productivity, Office, & Design Toolkits (10)
 *  8. Financial, Crypto, & Commerce Data (10)
 *  9. Cloud-Native Templates & Open Registries (4)
 * ════════════════════════════════════════════════════════════════════════════════
 */

export type McpCategory =
  | 'developer_docs'
  | 'search_crawlers'
  | 'databases'
  | 'social_comm'
  | 'cloud_devops'
  | 'security_osint'
  | 'productivity_office'
  | 'finance_commerce'
  | 'templates_registries';

export type McpAuthType = 'public' | 'api_key' | 'oauth';
export type McpTransportType = 'http' | 'sse';

export interface RemoteMcpServer {
  id: string;
  name: string;
  category: McpCategory;
  categoryLabel: string;
  url: string;
  transport: McpTransportType;
  authType: McpAuthType;
  authLabel: string;
  description: string;
  tools: string[];
  docsUrl?: string;
  isPopular?: boolean;
  isZeroAuth?: boolean;
}

export const MCP_CATEGORIES: { id: McpCategory | 'all' | 'zero_auth'; label: string; count?: number }[] = [
  { id: 'all', label: 'All 100 MCPs' },
  { id: 'zero_auth', label: 'Zero-Auth / Public' },
  { id: 'developer_docs', label: 'Developer Docs & Code' },
  { id: 'search_crawlers', label: 'Search & Crawlers' },
  { id: 'databases', label: 'Databases & Storage' },
  { id: 'social_comm', label: 'Social & Messaging' },
  { id: 'cloud_devops', label: 'Cloud & DevOps' },
  { id: 'security_osint', label: 'Security & OSINT' },
  { id: 'productivity_office', label: 'Productivity & Office' },
  { id: 'finance_commerce', label: 'Finance & Commerce' },
  { id: 'templates_registries', label: 'Templates & Registries' },
];

export const REMOTE_MCP_DIRECTORY: RemoteMcpServer[] = [
  // ── GROUP 1: Developer Docs, Code Repositories & Knowledge Engines (20) ────
  {
    id: 'deepwiki',
    name: 'DeepWiki Docs Explorer',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://index.mintlify.com/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Reads repository structures, schemas, and answers deep documentation questions for developer repositories.',
    tools: ['read_wiki_structure', 'read_wiki_contents', 'ask_question'],
    docsUrl: 'https://mintlify.com',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'mintlify-index',
    name: 'Mintlify Index',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://index.mintlify.com/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Live, verified technical API documentation and OpenAPI schema retriever across thousands of developer platforms.',
    tools: ['search_docs', 'get_endpoint_schema', 'read_guide'],
    docsUrl: 'https://mintlify.com',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'chainguard-academy',
    name: 'Chainguard Academy MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mcp.edu.chainguard.dev/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Security hardening, container provenance, Wolfi OS security, and CVE remediation guidance.',
    tools: ['lookup_cve', 'get_hardening_guide', 'inspect_image_sbom'],
    docsUrl: 'https://edu.chainguard.dev',
    isZeroAuth: true,
  },
  {
    id: 'devin-enterprise-wiki',
    name: 'Devin Enterprise Wiki',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://devin.ai/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Bearer Token',
    description: "Devin's private codebase indexing and multi-file code understanding server.",
    tools: ['query_repo_index', 'fetch_symbol_graph', 'explain_architecture'],
    docsUrl: 'https://devin.ai',
  },
  {
    id: 'github-remote',
    name: 'GitHub Remote MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://api.githubcopilot.com/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'GitHub Token / PAT',
    description: 'Manage PRs, issues, commits, branch trees, and code search over HTTPS without local Git binaries.',
    tools: ['search_code', 'get_pull_request', 'create_issue', 'list_commits'],
    docsUrl: 'https://github.com',
    isPopular: true,
  },
  {
    id: 'gitlab-public',
    name: 'GitLab Public MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://gitlab.com/api/v4/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'GitLab Token (Free)',
    description: 'Inspect CI/CD pipelines, review Merge Requests, and crawl file trees over standard HTTPS.',
    tools: ['get_pipeline_status', 'inspect_merge_request', 'read_repository_tree'],
    docsUrl: 'https://gitlab.com',
  },
  {
    id: 'context7',
    name: 'Context7 Library Explorer (Upstash)',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mcp.context7.com/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Real-time version-pinned framework and open-source package documentation retriever directly into model context.',
    tools: ['resolve_library_docs', 'fetch_api_reference', 'get_framework_examples'],
    docsUrl: 'https://context7.ai',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'devdocs-remote',
    name: 'DevDocs Remote MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://devdocs.io/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Search programming syntax, standard libraries, and language specs across 100+ languages.',
    tools: ['search_language_docs', 'lookup_standard_lib', 'get_syntax_example'],
    docsUrl: 'https://devdocs.io',
    isZeroAuth: true,
  },
  {
    id: 'stackoverflow-mcp',
    name: 'StackOverflow MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://api.stackexchange.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Search accepted answers, developer discussions, and debugging solutions for programming errors.',
    tools: ['search_questions', 'get_accepted_answer', 'query_tagged_posts'],
    docsUrl: 'https://stackexchange.com',
  },
  {
    id: 'mdn-web-docs',
    name: 'MDN Web Docs MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mdn-mcp.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Web specifications, HTML5/CSS3 rules, Web APIs, and JavaScript ECMAScript references.',
    tools: ['search_web_api', 'lookup_css_property', 'get_js_prototype_docs'],
    docsUrl: 'https://developer.mozilla.org',
    isZeroAuth: true,
  },
  {
    id: 'npm-registry',
    name: 'NPM Registry MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://npmjs.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Query Node.js package versions, bundle size metrics, dependency graphs, and download stats.',
    tools: ['query_package_info', 'inspect_dependencies', 'get_bundle_phobia_stats'],
    docsUrl: 'https://npmjs.org',
    isZeroAuth: true,
  },
  {
    id: 'pypi-checker',
    name: 'PyPI Package Index MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://pypi.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Python wheel metadata, release history, classifier tags, and maintainer records.',
    tools: ['search_pypi', 'get_package_releases', 'inspect_classifiers'],
    docsUrl: 'https://pypi.org',
    isZeroAuth: true,
  },
  {
    id: 'crates-io',
    name: 'Crates.io Rust MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mcp-hub.io/crates',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Rust crates, cargo.toml dependency references, docs.rs links, and vulnerability advisories.',
    tools: ['search_crates', 'get_crate_features', 'check_rustsec_advisories'],
    docsUrl: 'https://crates.io',
    isZeroAuth: true,
  },
  {
    id: 'go-packages',
    name: 'Go Packages MCP (pkg.go.dev)',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://golang.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Official Go package documentation, exported function signatures, and module dependency trees.',
    tools: ['search_go_pkg', 'read_godoc_signature', 'inspect_go_mod'],
    docsUrl: 'https://pkg.go.dev',
    isZeroAuth: true,
  },
  {
    id: 'dockerhub-mcp',
    name: 'DockerHub Registry MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://hub.docker.com/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Search official container images, tag manifests, architecture layers, and vulnerability scans.',
    tools: ['search_images', 'get_image_tags', 'inspect_dockerfile_layers'],
    docsUrl: 'https://hub.docker.com',
    isZeroAuth: true,
  },
  {
    id: 'huggingface-hub',
    name: 'Hugging Face Hub MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://huggingface.co/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Search open-source AI models, datasets, Spaces, and model card README documentation.',
    tools: ['search_models', 'get_model_card', 'list_dataset_splits'],
    docsUrl: 'https://huggingface.co',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'arxiv-research',
    name: 'ArXiv Research MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://arxiv.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Query scientific preprints, paper abstracts, author graphs, and arXiv PDF citations.',
    tools: ['search_arxiv_papers', 'get_abstract', 'list_recent_ai_preprints'],
    docsUrl: 'https://arxiv.org',
    isZeroAuth: true,
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://api.semanticscholar.org/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Pull academic paper citation graphs, TLDR summaries, and author publication metrics.',
    tools: ['search_citations', 'get_paper_tldr', 'get_author_h_index'],
    docsUrl: 'https://semanticscholar.org',
  },
  {
    id: 'openapi-spec-explorer',
    name: 'OpenAPI Spec Explorer',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mcp.run/openapi',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Validates, parses, and converts external Swagger/OpenAPI JSON/YAML links into callable schemas.',
    tools: ['parse_openapi_spec', 'list_endpoints', 'validate_swagger'],
    docsUrl: 'https://mcp.run',
    isZeroAuth: true,
  },
  {
    id: 'caniuse-mcp',
    name: 'CanIUse Browser Support MCP',
    category: 'developer_docs',
    categoryLabel: 'Developer Docs & Code',
    url: 'https://mcp-tools.io/caniuse',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Check CSS rules, HTML elements, and JavaScript Web API browser compatibility support matrices.',
    tools: ['check_feature_support', 'get_browser_matrix', 'lookup_baseline_status'],
    docsUrl: 'https://caniuse.com',
    isZeroAuth: true,
  },

  // ── GROUP 2: Web Search, Fetching & Public Crawlers (15) ────────────────────
  {
    id: 'parallel-search',
    name: 'Parallel Search MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://search.parallel.ai/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Live web search engine and clean Markdown content extractor optimized for LLM token ingestion without API keys.',
    tools: ['parallel_search', 'extract_clean_markdown', 'query_live_web'],
    docsUrl: 'https://parallel.ai',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'pocket-drives',
    name: 'Pocket Drives MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://pocketdrives.ai/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Search peer-to-peer luxury, exotic, and EV rental vehicles over remote HTTP with zero authentication.',
    tools: ['search_vehicles', 'get_rental_rates', 'filter_by_city'],
    docsUrl: 'https://pocketdrives.ai',
    isZeroAuth: true,
  },
  {
    id: 'vpnfail-fetcher',
    name: 'VPNFail Web Fetcher',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp.vpn.fail/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Fetches raw HTML and parsed Markdown content through a global proxy pool bypassing basic geoblocks.',
    tools: ['fetch_url_markdown', 'proxy_get_page', 'extract_structured_text'],
    docsUrl: 'https://vpn.fail',
    isZeroAuth: true,
  },
  {
    id: 'brightdata-crawler',
    name: 'Bright Data Remote MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp.brightdata.com',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free Tier (5K Req)',
    description: 'Enterprise anti-bot bypass proxy and structured web scraper for high-volume data harvesting.',
    tools: ['scrape_url', 'bypass_cloudflare', 'extract_ecom_products'],
    docsUrl: 'https://brightdata.com',
  },
  {
    id: 'tavily-search',
    name: 'Tavily Search MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp.tavily.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Search engine tailored specifically for LLM context ingestion with fast synthesis and source grounding.',
    tools: ['tavily_search', 'tavily_extract', 'tavily_qna'],
    docsUrl: 'https://tavily.com',
    isPopular: true,
  },
  {
    id: 'brave-search-remote',
    name: 'Brave Search Remote',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://search.mcp.brave.com/sse',
    transport: 'sse',
    authType: 'api_key',
    authLabel: 'Free Tier Key',
    description: 'Independent search index with zero user tracking and comprehensive web document ranking.',
    tools: ['brave_web_search', 'brave_local_search', 'brave_news_search'],
    docsUrl: 'https://brave.com',
    isPopular: true,
  },
  {
    id: 'exa-ai-search',
    name: 'Exa AI Neural Search',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp.exa.ai/sse',
    transport: 'sse',
    authType: 'api_key',
    authLabel: 'Free Tier Key',
    description: 'Embeddings-based neural search engine designed for deep research, code snippets, and research blogs.',
    tools: ['search_and_contents', 'find_similar_links', 'get_contents_by_id'],
    docsUrl: 'https://exa.ai',
    isPopular: true,
  },
  {
    id: 'duckduckgo-hosted',
    name: 'DuckDuckGo MCP (Hosted)',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp-gateway.com/ddg',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Anonymous web queries, instant answers, and zero-tracking search queries over HTTPS.',
    tools: ['ddg_query', 'get_instant_answer', 'search_news'],
    docsUrl: 'https://duckduckgo.com',
    isZeroAuth: true,
  },
  {
    id: 'wayback-machine',
    name: 'Wayback Machine Archive MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp.org/archive',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Pull historical archives and past revisions of any URL from web.archive.org.',
    tools: ['get_snapshots', 'fetch_archived_page', 'save_to_archive'],
    docsUrl: 'https://web.archive.org',
    isZeroAuth: true,
  },
  {
    id: 'wikipedia-knowledge',
    name: 'Wikipedia Knowledge Base',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp-services.io/wikipedia',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Semantic search, section parsing, and raw article text retrieval across Wikipedia encyclopedia.',
    tools: ['search_wikipedia', 'get_article_sections', 'get_summary'],
    docsUrl: 'https://wikipedia.org',
    isZeroAuth: true,
  },
  {
    id: 'wikidata-sparql',
    name: 'Wikidata SPARQL MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://wikidata.org/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Structured entity relationships, ontology graphs, and SPARQL endpoint query execution.',
    tools: ['execute_sparql', 'lookup_entity_id', 'get_claims'],
    docsUrl: 'https://wikidata.org',
    isZeroAuth: true,
  },
  {
    id: 'hacker-news-reader',
    name: 'Hacker News Reader MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp-hub.com/hn',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Fetch top stories, Algolia search indexes, algorithmic comments, and Ask HN submissions.',
    tools: ['get_top_stories', 'get_story_comments', 'search_hn_stories'],
    docsUrl: 'https://news.ycombinator.com',
    isZeroAuth: true,
  },
  {
    id: 'reddit-public-stream',
    name: 'Reddit Public Stream MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp-tools.net/reddit',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Free OAuth Client',
    description: 'Subreddit posts, comment sorting, community sentiment analysis, and topic trends.',
    tools: ['get_subreddit_top', 'search_reddit', 'get_thread_comments'],
    docsUrl: 'https://reddit.com',
  },
  {
    id: 'jina-reader',
    name: 'Jina AI Reader Remote',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://r.jina.ai/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Turns any target URL or web document into structured, clean, LLM-friendly Markdown formatting.',
    tools: ['read_url_as_markdown', 'extract_structured_article', 'search_jina'],
    docsUrl: 'https://jina.ai',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'rss-atom-parser',
    name: 'RSS / Atom Feed Parser MCP',
    category: 'search_crawlers',
    categoryLabel: 'Search & Crawlers',
    url: 'https://mcp-engine.com/rss',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Poll and ingest structured blog posts, changelogs, and news RSS feeds automatically.',
    tools: ['parse_feed_url', 'get_latest_articles', 'detect_feed_updates'],
    docsUrl: 'https://mcp-engine.com',
    isZeroAuth: true,
  },

  // ── GROUP 3: Database Connectors & Storage Engines (10) ────────────────────
  {
    id: 'supabase-database',
    name: 'Supabase Database MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://supabase.com/api/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Supabase Key',
    description: 'Browse database schemas, execute SQL queries, test Row Level Security (RLS), and run migrations.',
    tools: ['run_sql_query', 'get_schema_tables', 'test_rls_policies'],
    docsUrl: 'https://supabase.com',
    isPopular: true,
  },
  {
    id: 'neon-postgres',
    name: 'Neon Postgres Serverless',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://mcp.neon.tech',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Neon API Key',
    description: 'High-speed serverless PostgreSQL database operations, branching, and automated schema generation.',
    tools: ['execute_postgres_query', 'create_database_branch', 'inspect_table_columns'],
    docsUrl: 'https://neon.tech',
    isPopular: true,
  },
  {
    id: 'zilliz-milvus',
    name: 'Zilliz / Milvus Vector Hub',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://cloud.zilliz.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Zilliz API Key',
    description: 'Perform vector similarity search, query embeddings, and maintain semantic memory indexes.',
    tools: ['vector_similarity_search', 'insert_embeddings', 'create_collection'],
    docsUrl: 'https://zilliz.com',
  },
  {
    id: 'pinecone-vector',
    name: 'Pinecone Vector Store MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://mcp.pinecone.io',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Pinecone Key',
    description: 'Query dense/sparse vector embeddings and reference long-term memory blocks.',
    tools: ['query_vectors', 'upsert_vector_records', 'describe_index_stats'],
    docsUrl: 'https://pinecone.io',
  },
  {
    id: 'mongodb-atlas',
    name: 'MongoDB Atlas Remote MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://cloud.mongodb.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Atlas API Key',
    description: 'Manage document collections, run aggregate pipelines, and query JSON BSON documents.',
    tools: ['find_documents', 'run_aggregate_pipeline', 'list_collections'],
    docsUrl: 'https://mongodb.com',
  },
  {
    id: 'redis-cache',
    name: 'Redis Cache & KV Engine',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://mcp.upstash.com/redis',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Upstash / Redis Key',
    description: 'Fetch fast key-value data structures, Pub/Sub channels, and transient agent variables.',
    tools: ['redis_get', 'redis_set', 'redis_hgetall', 'redis_keys'],
    docsUrl: 'https://upstash.com',
  },
  {
    id: 'clickhouse-analytics',
    name: 'ClickHouse Analytical DB',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://clickhouse.cloud/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'ClickHouse Cloud Key',
    description: 'Run complex big-data analytical groupings, column-oriented metrics, and event log queries.',
    tools: ['run_analytical_query', 'get_table_partitions', 'inspect_query_plan'],
    docsUrl: 'https://clickhouse.com',
  },
  {
    id: 'prisma-orm',
    name: 'Prisma Schema & Client MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://mcp.prisma.io',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Inspect, validate, and generate schema migration maps and Prisma model definitions.',
    tools: ['validate_schema', 'generate_model_crud', 'diff_migrations'],
    docsUrl: 'https://prisma.io',
    isZeroAuth: true,
  },
  {
    id: 'airtable-tables',
    name: 'Airtable Remote Tables MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://api.airtable.com/v0/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Airtable PAT',
    description: 'Treat visual cloud spreadsheets and relational grid views as database sources.',
    tools: ['list_records', 'create_record', 'update_fields', 'search_views'],
    docsUrl: 'https://airtable.com',
  },
  {
    id: 'sqlite-isolated',
    name: 'SQLite Cloud / Turso MCP',
    category: 'databases',
    categoryLabel: 'Databases & Storage',
    url: 'https://api.turso.tech/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Turso Token (Free)',
    description: 'Handle edge-replicated SQLite databases with high performance and minimal memory footprint.',
    tools: ['execute_sql', 'get_tables', 'dump_schema'],
    docsUrl: 'https://turso.tech',
  },

  // ── GROUP 4: Social Media & Communication APIs (11) ────────────────────────
  {
    id: 'postsyncer-hub',
    name: 'PostSyncer Social Hub',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://postsyncer.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'PostSyncer Key',
    description: 'Connect to schedule, draft, publish, and read engagement metrics across 11 social networks.',
    tools: ['schedule_post', 'get_engagement_metrics', 'publish_broadcast'],
    docsUrl: 'https://postsyncer.com',
    isPopular: true,
  },
  {
    id: 'sendgrid-suite',
    name: 'SendGrid Delivery Suite',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.sendgrid.com/v3/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'SendGrid Key',
    description: '58 core tools covering transactional email generation, template rendering, and delivery tracking.',
    tools: ['send_transactional_email', 'get_delivery_stats', 'render_template'],
    docsUrl: 'https://sendgrid.com',
  },
  {
    id: 'slack-webhook-engine',
    name: 'Slack Webhook Engine',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://slack.com/api/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Slack Bot Token',
    description: 'Read channels, find workspace users, post rich interactive blocks, and listen to conversation threads.',
    tools: ['post_chat_message', 'list_public_channels', 'get_thread_replies'],
    docsUrl: 'https://slack.com',
  },
  {
    id: 'discord-gateway',
    name: 'Discord Bot Gateway',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://discord.com/api/v10/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Discord Bot Token',
    description: 'Monitor community channels, send embed cards, manage server roles, and coordinate logs.',
    tools: ['send_channel_message', 'get_guild_members', 'create_channel_thread'],
    docsUrl: 'https://discord.com',
  },
  {
    id: 'telegram-bot-hub',
    name: 'Telegram Bot Hub MCP',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.telegram.org/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Telegram Bot Token',
    description: 'Receive custom automated system updates, send formatted messages, and poll bot updates directly.',
    tools: ['send_message', 'send_photo', 'get_updates', 'send_inline_keyboard'],
    docsUrl: 'https://telegram.org',
  },
  {
    id: 'twilio-comm',
    name: 'Twilio Communication Framework',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.twilio.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Twilio SID / Secret',
    description: 'Trigger programmatic SMS messages, voice calls, and verify phone number delivery records.',
    tools: ['send_sms', 'make_voice_call', 'lookup_phone_carrier'],
    docsUrl: 'https://twilio.com',
  },
  {
    id: 'twitter-x-automator',
    name: 'X (Twitter) Automator',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.twitter.com/2/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'X OAuth 2.0',
    description: 'Extract trending topics, post threads, query user timelines, and analyze mention sentiment.',
    tools: ['post_tweet', 'get_trending_topics', 'search_recent_tweets'],
    docsUrl: 'https://x.com',
  },
  {
    id: 'linkedin-profile-scan',
    name: 'LinkedIn Profile Scan',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.linkedin.com/v2/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'LinkedIn Token',
    description: 'Gather open, structured professional profile summaries, company updates, and post analytics.',
    tools: ['get_profile_summary', 'post_company_update', 'get_share_analytics'],
    docsUrl: 'https://linkedin.com',
  },
  {
    id: 'mailchimp-manager',
    name: 'Mailchimp List Manager',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://mailchimp.com/api/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Mailchimp Key',
    description: 'Organize subscriber lists, launch email campaigns, and inspect campaign open/click rates.',
    tools: ['add_list_member', 'create_campaign', 'get_campaign_report'],
    docsUrl: 'https://mailchimp.com',
  },
  {
    id: 'whatsapp-business',
    name: 'WhatsApp Business API MCP',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://graph.facebook.com/v18.0/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Meta Access Token',
    description: 'Interface directly with active customer conversation threads and send approved template notifications.',
    tools: ['send_whatsapp_message', 'send_template_message', 'mark_read'],
    docsUrl: 'https://business.whatsapp.com',
  },
  {
    id: 'notion-workspace',
    name: 'Notion Workspace Client',
    category: 'social_comm',
    categoryLabel: 'Social & Messaging',
    url: 'https://api.notion.com/v1/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Notion Integration Key',
    description: 'Fetch, alter, or append complex database pages, kanban boards, and markdown blocks in Notion.',
    tools: ['query_database', 'append_block_children', 'create_page', 'search_titles'],
    docsUrl: 'https://notion.so',
    isPopular: true,
  },

  // ── GROUP 5: Cloud, Infrastructure, & DevOps Tools (10) ────────────────────
  {
    id: 'kubernetes-controller',
    name: 'Kubernetes Cluster Controller',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://mcp.k8s.io',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Kubeconfig Token',
    description: 'Inspect running pods, namespace events, diagnostic system logs, and node resource metrics.',
    tools: ['get_pods', 'get_pod_logs', 'describe_deployment', 'get_cluster_events'],
    docsUrl: 'https://kubernetes.io',
  },
  {
    id: 'aws-resource-scanner',
    name: 'AWS Resource Scanner',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://mcp.aws.amazon.com',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'AWS IAM Credentials',
    description: 'Review S3 storage containers, Lambda execution logs, and EC2 instance metrics.',
    tools: ['list_s3_buckets', 'get_lambda_metrics', 'describe_ec2_instances'],
    docsUrl: 'https://aws.amazon.com',
  },
  {
    id: 'google-cloud-console',
    name: 'Google Cloud Console Integrator',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://cloudfunctions.googleapis.com/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'GCP OAuth 2.0',
    description: 'Verify active Cloud Run configurations, Cloud Function triggers, and Cloud Logging traces.',
    tools: ['list_cloud_run_services', 'get_cloud_logs', 'inspect_service_status'],
    docsUrl: 'https://cloud.google.com',
  },
  {
    id: 'render-deployment',
    name: 'Render Deployment Platform',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://api.render.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Render API Key',
    description: 'Monitor ongoing web service builds, deploy previews, and trigger manual project redeployments.',
    tools: ['list_services', 'trigger_deploy', 'get_deploy_logs'],
    docsUrl: 'https://render.com',
  },
  {
    id: 'docker-container-manager',
    name: 'Docker Container Manager',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://mcp.docker.io/daemon',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'List active microservices, inspect container networks, and retrieve terminal streams.',
    tools: ['list_containers', 'get_container_stats', 'inspect_network'],
    docsUrl: 'https://docker.com',
    isZeroAuth: true,
  },
  {
    id: 'vercel-project-control',
    name: 'Vercel Project Control',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://api.vercel.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Vercel Token',
    description: 'Update project environment variables, manage domain DNS bindings, and check build statuses.',
    tools: ['list_deployments', 'set_environment_variable', 'get_domain_dns_status'],
    docsUrl: 'https://vercel.com',
    isPopular: true,
  },
  {
    id: 'cloudflare-dns-router',
    name: 'Cloudflare DNS Router',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://api.cloudflare.com/client/v4/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Cloudflare API Token',
    description: 'Modify zone DNS records, manage Worker routes, and inspect security firewall analytics.',
    tools: ['list_dns_records', 'create_dns_record', 'get_zone_analytics'],
    docsUrl: 'https://cloudflare.com',
  },
  {
    id: 'datadog-monitor',
    name: 'Datadog Monitor Platform',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://api.datadoghq.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Datadog App Key',
    description: 'Track microservice APM errors, query log aggregation metrics, and visualize execution traces.',
    tools: ['query_metrics', 'get_active_monitors', 'search_apm_traces'],
    docsUrl: 'https://datadoghq.com',
  },
  {
    id: 'grafana-sync',
    name: 'Grafana Dashboard Sync',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://grafana.com/api/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Grafana Service Key',
    description: 'Fetch real-time service health panels, render dashboard graphs, and inspect alert rules.',
    tools: ['get_dashboard_panel', 'query_prometheus_datasource', 'list_alert_rules'],
    docsUrl: 'https://grafana.com',
  },
  {
    id: 'netlify-host-hub',
    name: 'Netlify Host Hub MCP',
    category: 'cloud_devops',
    categoryLabel: 'Cloud & DevOps',
    url: 'https://api.netlify.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Netlify Token',
    description: 'Manage static frontend sites, edge functions, form submissions, and webhook hooks.',
    tools: ['list_sites', 'get_site_deploys', 'inspect_form_submissions'],
    docsUrl: 'https://netlify.com',
  },

  // ── GROUP 6: OSINT, Cyber Security, & Data Validation (10) ──────────────────
  {
    id: 'osint-toolkit',
    name: 'OSINT Toolkit Wrapper',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://mcp.osint.tools/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Integrates classic intelligence tools (Sherlock, Maigret, theHarvester) under one remote endpoint.',
    tools: ['search_username_footprint', 'harvest_domain_emails', 'lookup_pgp_keys'],
    docsUrl: 'https://osint.tools',
    isZeroAuth: true,
  },
  {
    id: 'haveibeenpwned',
    name: 'HaveIBeenPwned Breach Checker',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://haveibeenpwned.com/api/v3/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'HIBP Key ($3.50/mo)',
    description: 'Check if specific email addresses, domains, or credentials have been compromised in data breaches.',
    tools: ['check_breached_account', 'get_domain_breaches', 'check_pwned_password_hash'],
    docsUrl: 'https://haveibeenpwned.com',
  },
  {
    id: 'virustotal-analyzer',
    name: 'VirusTotal Domain & File Analyzer',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://www.virustotal.com/api/v3/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Run SHA256 hash checks and scan suspect web links against 70+ antivirus threat databases.',
    tools: ['scan_url', 'get_file_report', 'lookup_domain_reputation'],
    docsUrl: 'https://virustotal.com',
  },
  {
    id: 'shodan-network',
    name: 'Shodan Network Search',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://api.shodan.io/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Shodan API Key',
    description: 'Locate internet-connected servers, open network ports, banner headers, and device vulnerabilities.',
    tools: ['host_search', 'lookup_ip_ports', 'query_exploit_db'],
    docsUrl: 'https://shodan.io',
  },
  {
    id: 'whois-explorer',
    name: 'Whois & RDAP Domain Explorer',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://mcp-hub.io/whois',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Look up domain registrar ownership details, nameservers, creation dates, and expiration profiles.',
    tools: ['lookup_whois', 'get_rdap_record', 'check_domain_availability'],
    docsUrl: 'https://mcp-hub.io',
    isZeroAuth: true,
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema Validator MCP',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://mcp.run/json-validator',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Instantly evaluate structural validity, JSON Schema Draft 7/2020-12 compliance, and formatting.',
    tools: ['validate_json_payload', 'generate_json_schema', 'format_json'],
    docsUrl: 'https://mcp.run',
    isZeroAuth: true,
  },
  {
    id: 'jwt-debugger',
    name: 'JWT Debugger & Signature Inspector',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://jwt.mcp.run/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Decode header/payload claims, check security expiration timestamps, and analyze JWT signature algorithms.',
    tools: ['decode_jwt', 'check_token_expiration', 'inspect_claims'],
    docsUrl: 'https://jwt.io',
    isZeroAuth: true,
  },
  {
    id: 'markdown-formatter',
    name: 'Markdown Formatter & Linter',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://mcp.run/markdown',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Parse messy documents, repair broken table alignments, and generate clean CommonMark outputs.',
    tools: ['format_markdown', 'repair_tables', 'lint_markdown_headings'],
    docsUrl: 'https://mcp.run',
    isZeroAuth: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Pattern Tester & Explainer',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://mcp.run/regex',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Build, evaluate, and confirm code-safe regular expression rules against test string matrices.',
    tools: ['test_regex_matches', 'explain_regex_tokens', 'generate_regex'],
    docsUrl: 'https://mcp.run',
    isZeroAuth: true,
  },
  {
    id: 'dns-dig-utility',
    name: 'DNS Dig Utility (Cloudflare/Google)',
    category: 'security_osint',
    categoryLabel: 'Security & OSINT',
    url: 'https://dns.mcp.run/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Query live DNS over HTTPS records (A, AAAA, MX, TXT, CNAME, NS, SOA, CAA, PTR) directly.',
    tools: ['dig_dns_record', 'lookup_mx_records', 'verify_spf_dkim_txt'],
    docsUrl: 'https://dns.mcp.run',
    isZeroAuth: true,
  },

  // ── GROUP 7: Productivity, Office, & Design Toolkits (10) ───────────────────
  {
    id: 'figma-reader',
    name: 'Figma Design Reader',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.figma.com/v1/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Figma Personal Token',
    description: 'Read structural canvas elements, inspect component layout tokens, CSS styles, and export SVG assets.',
    tools: ['get_file_nodes', 'extract_design_tokens', 'export_svg_component'],
    docsUrl: 'https://figma.com',
    isPopular: true,
  },
  {
    id: 'google-drive-explorer',
    name: 'Google Drive File Explorer',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://www.googleapis.com/drive/v3/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Google Workspace OAuth',
    description: 'Find documents, search spreadsheets, and extract text from shared cloud storage folders.',
    tools: ['search_drive_files', 'read_doc_content', 'export_sheet_as_csv'],
    docsUrl: 'https://drive.google.com',
  },
  {
    id: 'google-calendar-scheduler',
    name: 'Google Calendar Scheduler',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://www.googleapis.com/calendar/v3/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Google Calendar OAuth',
    description: 'Check upcoming meeting slots, schedule calendar events, and inspect team availability.',
    tools: ['list_upcoming_events', 'create_calendar_event', 'find_free_busy_slots'],
    docsUrl: 'https://calendar.google.com',
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365 Integration',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://graph.microsoft.com/v1.0/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'MS Graph OAuth',
    description: 'Access Outlook emails, update Excel online workbooks, and search OneDrive files.',
    tools: ['get_outlook_messages', 'update_excel_range', 'search_onedrive'],
    docsUrl: 'https://microsoft.com',
  },
  {
    id: 'todoist-manager',
    name: 'Todoist Task Manager',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.todoist.com/rest/v2/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Todoist API Token',
    description: 'Create task cards, organize projects, set due dates, and query daily priorities.',
    tools: ['create_task', 'list_tasks_by_due', 'close_task', 'get_projects'],
    docsUrl: 'https://todoist.com',
  },
  {
    id: 'trello-board',
    name: 'Trello Project Board MCP',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.trello.com/1/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Trello Key + Token',
    description: 'Move workflow cards across kanban lists, add checklists, and assign team members.',
    tools: ['get_board_lists', 'create_card', 'move_card_list', 'add_comment'],
    docsUrl: 'https://trello.com',
  },
  {
    id: 'asana-workflow',
    name: 'Asana Workflow Hub',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://app.asana.com/api/1.0/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Asana PAT Token',
    description: 'Track task deadlines, organize milestones, and update operational cross-functional dependencies.',
    tools: ['get_workspace_tasks', 'create_task', 'update_milestone_status'],
    docsUrl: 'https://asana.com',
  },
  {
    id: 'clickup-space',
    name: 'ClickUp Product Space',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.clickup.com/api/v2/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'ClickUp API Token',
    description: 'Sync sprint logs, update custom task fields, and maintain collaborative team documentation.',
    tools: ['get_space_lists', 'create_clickup_task', 'set_custom_field'],
    docsUrl: 'https://clickup.com',
  },
  {
    id: 'miro-canvas',
    name: 'Miro Collaborative Canvas',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.miro.com/v2/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Miro OAuth 2.0',
    description: 'Map visual user flows, place sticky notes, and extract wireframe board layout details.',
    tools: ['create_sticky_note', 'get_board_items', 'create_connector_line'],
    docsUrl: 'https://miro.com',
  },
  {
    id: 'zoom-manager',
    name: 'Zoom Meetings Manager',
    category: 'productivity_office',
    categoryLabel: 'Productivity & Office',
    url: 'https://api.zoom.us/v2/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Zoom Server OAuth',
    description: 'Generate instant video call links, list scheduled webinars, and retrieve cloud recordings.',
    tools: ['create_meeting', 'list_scheduled_meetings', 'get_recording_links'],
    docsUrl: 'https://zoom.us',
  },

  // ── GROUP 8: Financial, Crypto, & Commerce Data (10) ────────────────────────
  {
    id: 'coingecko-crypto',
    name: 'CoinGecko Crypto API MCP',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://api.coingecko.com/api/v3/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public (Free Tier)',
    description: 'Query real-time crypto valuations, market caps, gas fees, and historical token chart records.',
    tools: ['get_token_price', 'get_market_movers', 'get_historical_ohlcv'],
    docsUrl: 'https://coingecko.com',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'stripe-merchant',
    name: 'Stripe Merchant Gateway',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://api.stripe.com/v1/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Stripe Restricted Key',
    description: 'Review payment transactions, inspect customer invoices, and track active MRR/subscription metrics.',
    tools: ['list_invoices', 'get_customer_subscriptions', 'retrieve_payment_intent'],
    docsUrl: 'https://stripe.com',
    isPopular: true,
  },
  {
    id: 'shopify-store',
    name: 'Shopify Store Manager',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://api.shopify.com/admin/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Shopify Admin Token',
    description: 'Look up active product inventory catalogs, review orders, and inspect fulfillment tracking status.',
    tools: ['search_products', 'get_recent_orders', 'update_inventory_level'],
    docsUrl: 'https://shopify.com',
  },
  {
    id: 'yahoo-finance',
    name: 'Yahoo Finance Analytics MCP',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://finance.mcp.run/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Track daily stock ticker movements, balance sheet metrics, earnings calendars, and index stats.',
    tools: ['get_stock_quote', 'get_financial_statement', 'lookup_ticker_symbol'],
    docsUrl: 'https://finance.yahoo.com',
    isZeroAuth: true,
  },
  {
    id: 'open-exchange-rates',
    name: 'Open Exchange Rates (Forex)',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://openexchangerates.org/api/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Get real-time and historical currency exchange conversions across 170+ fiat currencies.',
    tools: ['convert_currency', 'get_latest_rates', 'get_historical_rate'],
    docsUrl: 'https://openexchangerates.org',
  },
  {
    id: 'alpha-vantage',
    name: 'Alpha Vantage Market Engine',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://www.alphavantage.co/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Free API Key',
    description: 'Fetch technical indicators (RSI, MACD, SMA), sector performance, and real-time equity data.',
    tools: ['get_technical_indicator', 'get_sector_performance', 'get_crypto_intraday'],
    docsUrl: 'https://alphavantage.co',
  },
  {
    id: 'plaid-banking',
    name: 'Plaid Banking Gateway',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://production.plaid.com/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Plaid Secret Key',
    description: 'Connect bank transaction categories, balances, and account data to personal accounting agents.',
    tools: ['get_account_balances', 'get_recent_transactions', 'get_institution_info'],
    docsUrl: 'https://plaid.com',
  },
  {
    id: 'coinbase-exchange',
    name: 'Coinbase Exchange API',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://api.coinbase.com/v2/mcp',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Coinbase API Key',
    description: 'Monitor live order book bids/asks, historical trades, and execute programmatic orders safely.',
    tools: ['get_order_book', 'get_product_ticker', 'list_supported_currencies'],
    docsUrl: 'https://coinbase.com',
  },
  {
    id: 'woocommerce-builder',
    name: 'WooCommerce API Builder',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://mcp.woocommerce.com',
    transport: 'http',
    authType: 'api_key',
    authLabel: 'Consumer Key/Secret',
    description: 'Sync self-hosted WordPress/WooCommerce shopping carts, orders, and customer records.',
    tools: ['list_woo_products', 'get_woo_orders', 'update_stock_quantity'],
    docsUrl: 'https://woocommerce.com',
  },
  {
    id: 'adsense-tracker',
    name: 'Google AdSense Tracker Hub',
    category: 'finance_commerce',
    categoryLabel: 'Finance & Commerce',
    url: 'https://adsense.googleapis.com/v2/mcp',
    transport: 'http',
    authType: 'oauth',
    authLabel: 'Google AdSense OAuth',
    description: 'Keep tabs on daily ad impressions, CTR, revenue splits, and top earning ad units.',
    tools: ['get_daily_earnings_report', 'list_ad_clients', 'get_ad_unit_metrics'],
    docsUrl: 'https://adsense.google.com',
  },

  // ── GROUP 9: Cloud-Native Templates & Open Registries (4) ──────────────────
  {
    id: 'val-town-registry',
    name: 'Val Town MCP Registry (150+ Scripts)',
    category: 'templates_registries',
    categoryLabel: 'Templates & Registries',
    url: 'https://val.town/v/mcp/hub',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Forkable community scripts with 1-click HTTPS serverless edge endpoints recommended by the core MCP team.',
    tools: ['search_community_vals', 'fork_mcp_template', 'test_remote_val'],
    docsUrl: 'https://val.town',
    isPopular: true,
    isZeroAuth: true,
  },
  {
    id: 'vercel-serverless-template',
    name: 'Vercel AI SDK MCP Serverless',
    category: 'templates_registries',
    categoryLabel: 'Templates & Registries',
    url: 'https://github.com/vercel/ai/tree/main/examples/mcp-serverless',
    transport: 'http',
    authType: 'public',
    authLabel: 'Open Source Template',
    description: 'Ready-to-deploy Next.js / Node.js template for running custom JavaScript MCP handlers as Vercel Edge functions.',
    tools: ['deploy_vercel_mcp', 'inspect_edge_config', 'test_sse_handler'],
    docsUrl: 'https://vercel.com/ai',
    isZeroAuth: true,
  },
  {
    id: 'cloudflare-workers-mcp',
    name: 'Cloudflare Workers Edge MCP',
    category: 'templates_registries',
    categoryLabel: 'Templates & Registries',
    url: 'https://github.com/cloudflare/workers-sdk/tree/main/templates/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Open Source Template',
    description: 'Ultra-low latency template utilizing standard Web Fetch APIs to handle MCP JSON-RPC requests via Cloudflare edge.',
    tools: ['deploy_worker_mcp', 'configure_wrangler', 'test_edge_rpc'],
    docsUrl: 'https://workers.cloudflare.com',
    isZeroAuth: true,
  },
  {
    id: 'safemcp-registry',
    name: 'SafeMCP & Glama Global Index',
    category: 'templates_registries',
    categoryLabel: 'Templates & Registries',
    url: 'https://safemcp.com/api/mcp',
    transport: 'http',
    authType: 'public',
    authLabel: 'Public / Zero-Auth',
    description: 'Verified public directory indexing over 28,000 community Model Context Protocol packages and remote tools.',
    tools: ['search_safemcp_registry', 'get_server_security_rating', 'query_glama_hub'],
    docsUrl: 'https://safemcp.com',
    isPopular: true,
    isZeroAuth: true,
  },
];

/**
 * Helper Utilities
 */
export function getAllMcpServers(): RemoteMcpServer[] {
  return REMOTE_MCP_DIRECTORY;
}

export function getZeroAuthMcpServers(): RemoteMcpServer[] {
  return REMOTE_MCP_DIRECTORY.filter(s => s.isZeroAuth || s.authType === 'public');
}

export function getMcpServersByCategory(category: McpCategory | 'all' | 'zero_auth'): RemoteMcpServer[] {
  if (category === 'all') return REMOTE_MCP_DIRECTORY;
  if (category === 'zero_auth') return getZeroAuthMcpServers();
  return REMOTE_MCP_DIRECTORY.filter(s => s.category === category);
}

export function searchMcpServers(query: string, category: McpCategory | 'all' | 'zero_auth' = 'all'): RemoteMcpServer[] {
  let list = getMcpServersByCategory(category);
  const q = query.trim().toLowerCase();
  if (!q) return list;

  return list.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.id.toLowerCase().includes(q) ||
    s.url.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.categoryLabel.toLowerCase().includes(q) ||
    s.tools.some(t => t.toLowerCase().includes(q))
  );
}

/**
 * Export standard mcpServers JSON configuration block for Cursor, Windsurf, Claude Desktop, LibreChat, Devin
 */
export function generateMcpServersJson(servers: RemoteMcpServer[]): string {
  const mcpServers: Record<string, any> = {};
  for (const s of servers) {
    if (s.authType === 'public') {
      mcpServers[s.id] = {
        type: s.transport === 'sse' ? 'sse' : 'http',
        url: s.url,
      };
    } else {
      mcpServers[s.id] = {
        type: s.transport === 'sse' ? 'sse' : 'http',
        url: s.url,
        headers: {
          Authorization: 'Bearer <YOUR_API_KEY>',
        },
      };
    }
  }
  return JSON.stringify({ mcpServers }, null, 2);
}

/**
 * Generate Claude Code CLI commands (claude mcp add --transport http ...)
 */
export function generateClaudeCliCommands(servers: RemoteMcpServer[]): string {
  return servers
    .map(s => `claude mcp add --transport ${s.transport === 'sse' ? 'sse' : 'http'} ${s.id} ${s.url}`)
    .join('\n');
}
